### PR TITLE
Fixes #82

### LINKED ISSUE #82: Critical memory leak
**Describe the bug**
Memory leak. Detached DOM nodes are not cleared from memory. Nodes are not in DOM but javascript still has reference to them so they can not be cleared by garbage collector.

**To Reproduce**
Memory leak appears on umounting/mounting of react-horizontal-scrolling-menu component. 
To reproduce just open [demo page](https://asmyshlyaev177.github.io/react-horizontal-scrolling-menu) and click toggle button many times.
Observe amount of DOM nodes in devtools -> performance monitor tab.
You will notice that the nodes are increasing all the time and not decreasing.
Nov-27-2019 18-36-41

details about "detached DOM tree memory leaks"
https://developers.google.com/web/tools/chrome-devtools/memory-problems/#discover_detached_dom_tree_memory_leaks_with_heap_snapshots

### PR DESCRIPTION
**Pull request by NeXTs**
Passing same function to document.addEventListener and react caused memory lead. I've just added wrapper function for document.addEventLister which eventually call proper functions. Also with that passiveEvents feature memory was leaked too, probably when you set third parameter in addEventListener - exact same object must be passed to removeEventListener as third parameter.. I am not sure so I just removed it, revert it back if you need it.

### CODE REVIEW

File: src/scrollMenu.tsx [hunk 1]
```diff
@@ -967,6 +959,13 @@ export class ScrollMenu extends React.Component<MenuProps, MenuState> {
     });
   }
 
+  /** wrapper for handleDrag event to avoid memory leak */
+  public handleDragWrapper = (
+    e: Event,
+  ): Void => {
+    this.handleDrag();
```
Comment (asmyshlyaev177) [inline src/scrollMenu.tsx]:
```suggestion
    this.handleDrag(e);
```

File: src/scrollMenu.tsx [hunk 2]
```diff
@@ -967,6 +959,13 @@ export class ScrollMenu extends React.Component<MenuProps, MenuState> {
     });
   }
 
+  /** wrapper for handleDrag event to avoid memory leak */
+  public handleDragWrapper = (
+    e: Event,
```
Comment (asmyshlyaev177) [inline src/scrollMenu.tsx]:
```suggestion
    e: React.MouseEvent | React.TouchEvent | Event,
```

File: src/scrollMenu.tsx (hunk 1 above)
Comment (NeXTs) [reply src/scrollMenu.tsx]: missed that, sorry )

File: src/scrollMenu.tsx (hunk 2 above)
Comment (NeXTs) [reply src/scrollMenu.tsx]: "React.MouseEvent | React.TouchEvent" it was deleted intentionally because handleDragWrapper called only by document.addEventListener, not by react

**Comment by asmyshlyaev177** [comment]
It's ok now i think.
